import '@/styles/globals.css'
import { Montserrat } from 'next/font/google'
import Head from 'next/head' 
// Assuming the NavBar.js file is in the src/components directory
import NavBar from '../components/NavBar';
import '../styles/globals.css';
import Footer from '../components/Footer';
import { AnimatePresence } from 'framer-motion';
import { useRouter } from 'next/router';

// ... rest of your code

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont'
})
export default function App({ Component, pageProps }) {
  const router = useRouter();
  return (
   <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        
        <main className={`${montserrat.variable} font-mont bg-light dark:bg-dark w-full min-h-screen`}>
            <NavBar/>
            <AnimatePresence mode='wait'>
            <Component key={router.asPath} {...pageProps}/>
            </AnimatePresence>
            <Footer />
        </main>
   </>
  );
}
